name: jewelry_shop_dart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.14.0
  firebase_options: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/profile.png
